"""Steganographic hide/extract engine.

Glossary
--------
* hide (sender side):  embed coded bits into a sequence of LLM-generated tokens.
* extract (receiver side): recover coded bits from a token sequence.

Both sides must use exactly the same:
  - backend (model, tokenizer, revision)
  - prompt (context prefix)
  - SteganographyConfig (top_k, total)

The engine itself is model-neutral; it uses only the LanguageModelBackend
Protocol from lsteg.model.interface.
"""

from __future__ import annotations

from collections.abc import Sequence
from dataclasses import dataclass

from lsteg.coding.range_coder import CodedBits, RangeDecoder, RangeEncoder
from lsteg.model.interface import LanguageModelBackend
from lsteg.steg.frequencies import DEFAULT_TOP_K, FREQUENCY_TOTAL, logits_to_frequency_table


class CoverTokenError(RuntimeError):
    """A cover token is not in the active top-k alphabet."""


@dataclass(frozen=True, slots=True)
class SteganographyConfig:
    """Shared parameters that both sender and receiver must agree on."""

    top_k: int = DEFAULT_TOP_K
    frequency_total: int = FREQUENCY_TOTAL

    def __post_init__(self) -> None:
        from lsteg.coding.frequencies import MAX_FREQUENCY_TOTAL

        if not (1 <= self.top_k <= self.frequency_total):
            raise ValueError(
                f"top_k must satisfy 1 <= top_k <= frequency_total, "
                f"got top_k={self.top_k}, frequency_total={self.frequency_total}"
            )
        if self.frequency_total > MAX_FREQUENCY_TOTAL:
            raise ValueError(
                f"frequency_total must be <= {MAX_FREQUENCY_TOTAL}, got {self.frequency_total}"
            )


def hide(
    backend: LanguageModelBackend,
    prompt: str,
    coded_bits: CodedBits,
    *,
    config: SteganographyConfig | None = None,
    max_tokens: int = 4096,
) -> list[int]:
    """Embed ``coded_bits`` into a token sequence generated from ``prompt``.

    Parameters
    ----------
    backend:
        LLM backend satisfying the LanguageModelBackend protocol.
    prompt:
        Cover text prefix; the model conditions all generation on this.
    coded_bits:
        The secret payload already encoded as a CodedBits object.
    config:
        Steganographic parameters; must match what the receiver uses.
    max_tokens:
        Hard upper bound on generated tokens to prevent infinite loops.

    Returns
    -------
    list[int]
        The generated cover token IDs (not including the prompt tokens).
    """
    cfg = config or SteganographyConfig()
    token_ids = backend.tokenize(prompt)
    decoder = RangeDecoder(coded_bits)

    cover_tokens: list[int] = []
    needed_bits = coded_bits.bit_length + 32  # 32-bit Range Decoder lookahead

    for _ in range(max_tokens):
        logits = backend.next_logits(token_ids)
        top_ids, table = logits_to_frequency_table(
            list(logits),
            top_k=cfg.top_k,
            total=cfg.frequency_total,
        )

        symbol_index = decoder.decode(table)
        token_id = top_ids[symbol_index]

        token_ids.append(token_id)
        cover_tokens.append(token_id)

        # Stop once the decoder has consumed all meaningful bits plus the
        # 32-bit lookahead that the Range Decoder needs to initialise.
        bits_consumed = decoder._reader._position  # noqa: SLF001
        if bits_consumed >= needed_bits:
            break

        # Also stop on EOS tokens (Qwen3: 151643=<|endoftext|>, 151645=<|im_end|>)
        if token_id in (151643, 151645):
            break

    return cover_tokens


def extract(
    backend: LanguageModelBackend,
    prompt: str,
    cover_tokens: Sequence[int],
    *,
    config: SteganographyConfig | None = None,
) -> CodedBits:
    """Recover the coded bits from ``cover_tokens`` generated by :func:`hide`.

    Parameters
    ----------
    backend:
        Must be the same model, revision, and tokenizer as used when hiding.
    prompt:
        Must be the same prompt string as used when hiding.
    cover_tokens:
        The token IDs returned by :func:`hide` (not including prompt tokens).
    config:
        Must be the same config as used when hiding.

    Returns
    -------
    CodedBits
        The recovered bits.  The caller is responsible for decoding the payload
        (decompress, decrypt, unframe) using the appropriate codec layer.

    Raises
    ------
    CoverTokenError
        If a cover token is not found in the top-k alphabet at some position.
        This indicates a mismatch between hide/extract parameters.
    """
    cfg = config or SteganographyConfig()
    token_ids = backend.tokenize(prompt)
    encoder = RangeEncoder()

    for token_id in cover_tokens:
        logits = backend.next_logits(token_ids)
        top_ids, table = logits_to_frequency_table(
            list(logits),
            top_k=cfg.top_k,
            total=cfg.frequency_total,
        )

        if token_id not in top_ids:
            raise CoverTokenError(
                f"Cover token {token_id!r} is not in the top-{cfg.top_k} alphabet "
                f"at position {len(token_ids) - len(backend.tokenize(prompt))}. "
                "This may indicate a parameter mismatch between hide() and extract()."
            )

        symbol_index = top_ids.index(token_id)
        encoder.encode(table, symbol_index)
        token_ids.append(token_id)

    return encoder.finish()
